# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
name: prometheus-operator
version: 0.1.0

dependencies:
- name: kube-prometheus-stack
  version: 80.14.4
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-blackbox-exporter
  version: 11.6.1
  repository: https://prometheus-community.github.io/helm-charts
