# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/cert.yaml
- ./resources/delegation.yaml
- ./resources/httpproxy.yaml
- ./resources/service.yaml
- ./resources/statefulset.yaml
