LogLevel = "INFO"
ArtistArtPriority = "artist.*, folder.*, album/artist.*, external"  # compatibility with Jellyfin convention
AutoImportPlaylists = false
ImageCacheSize = "1024MB"
TranscodingCacheSize = "100MB"
CacheFolder = "/cache"
CoverArtPriority = "cover.*"  # strict

[Backup]
Path = "/backup"
Count = 7
Schedule =  "0 0 * * *"  # daily at midnight

[Prometheus]
Enabled = true
MetricsPath = "/metrics"

[Scanner]
Enabled = true
Schedule = "0 * * * *"
ScanOnStartup = false
PurgeMissing = "always"

[Subsonic]
ArtistParticipations = true
